// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnlMu3DBl7GyJthINPUv_aRr97pgD5DOQ',
    appId: '1:801665695706:web:93c8d7c438a937f29bcae3',
    messagingSenderId: '801665695706',
    projectId: 'our-bus-tracker',
    authDomain: 'our-bus-tracker.firebaseapp.com',
    databaseURL: 'https://our-3bus-tracker-1e14a.asia-southeast1.firebasedatabase.app/',
    storageBucket: 'our-bus-tracker.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA9LlaGgLImh3UTIGCJ64Z_cCYfbFnMqfA',
    appId: '1:801665695706:android:1df24aabc6cda4989bcae3',
    messagingSenderId: '801665695706',
    projectId: 'our-bus-tracker',
    databaseURL: 'https://our-bus-tracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'our-bus-tracker.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4MOmBkoISV9rpjRwZNkrRhE4Y37uLPHY',
    appId: '1:801665695706:ios:140bc3abc71fb6f49bcae3',
    messagingSenderId: '801665695706',
    projectId: 'our-bus-tracker',
    databaseURL: 'https://our-bus-tracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'our-bus-tracker.firebasestorage.app',
    iosBundleId: 'com.example.collegeBusTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4MOmBkoISV9rpjRwZNkrRhE4Y37uLPHY',
    appId: '1:801665695706:ios:140bc3abc71fb6f49bcae3',
    messagingSenderId: '801665695706',
    projectId: 'our-bus-tracker',
    databaseURL: 'https://our-bus-tracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'our-bus-tracker.firebasestorage.app',
    iosBundleId: 'com.example.collegeBusTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnlMu3DBl7GyJthINPUv_aRr97pgD5DOQ',
    appId: '1:801665695706:web:93c8d7c438a937f29bcae3',
    messagingSenderId: '801665695706',
    projectId: 'our-bus-tracker',
    authDomain: 'our-bus-tracker.firebaseapp.com',
    databaseURL: 'https://our-bus-tracker-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'our-bus-tracker.firebasestorage.app',
  );

}